apiVersion: v1
kind: Namespace
metadata:
  name:  test
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: db-config
  namespace: test
data:
   DB_HOST: "node-sql-svc"
   DB_NAME: "test_db"
---
apiVersion: v1 
kind: Secret 
metadata:
  name: db-secret
  namespace: test
data:
   DB_USER: cm9vdA==
   DB_PASSWORD: cGFzc3dvcmQ=
   DB_PASSWORD_ROOT: cGFzc3dvcmQ=
   DB_URL: bXlzcWw6Ly9yb290OnBhc3N3b3JkQG15c3FsOjMzMDYvdGVzdF9kYg==
type: Opaque
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-ss
  namespace: test
spec:
  replicas: 2
  serviceName: node-sql-svc
  updateStrategy:
    type: RollingUpdate 
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app:node
    spec:
      containers:
        - name: sql-container
          image: mysql
          ports:
            - containerPort: 3306
              name: sql-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD_ROOT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
          volumeMounts:
            - name: sql-volume
              mountPath: /ebs
  volumeClaimTemplates:
    - metadata:
        name: sql-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp3
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1 
kind: Service 
metadata:
  name: node-sql-svc
  namespace: test
spec:
  clusterIP: None
  selector: 
    app: node
  ports:
    - name: svc 
      port: 3306
      targetPort: sql-port
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: app-deploy
  namespace: test
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: docker-container
          image: venkaiahk/node-three-tier:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          restartPolicy: OnFailure
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_URL
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
---
apiVersion: v1 
kind: Service 
metadata:
  name: app-svc
  namespace: test
spec:
  type: NodePort
  selector:
    app: front-end
  ports:  
    - name: app-port
      ports: 3000
      targetPort: 3000
      protocol: TCP
            



